spring.application.name=ContactHub

spring.datasource.url=jdbc:postgresql://localhost:5432/contacthubDB
spring.datasource.username=postgres
spring.datasource.password=noemak
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true