--
-- PostgreSQL database dump
--

\restrict AY6Db4az4u9AhcN7pvMphBrH0iJ5dYK7GoguTT9l3JFyW6M1y3JxqsbREG6aZst

-- Dumped from database version 18.4
-- Dumped by pg_dump version 18.4

-- Started on 2026-07-30 23:10:48

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: pg_database_owner
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO pg_database_owner;

--
-- TOC entry 4921 (class 0 OID 0)
-- Dependencies: 4
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: pg_database_owner
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 222 (class 1259 OID 16488)
-- Name: contacts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.contacts (
    id bigint NOT NULL,
    address character varying(255),
    created_at timestamp(6) without time zone NOT NULL,
    email character varying(255) NOT NULL,
    first_name character varying(255) NOT NULL,
    is_favourite boolean CONSTRAINT contacts_is_favorite_not_null NOT NULL,
    last_name character varying(255),
    phone character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.contacts OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 16487)
-- Name: contacts_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.contacts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contacts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 16447)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    email character varying(255) NOT NULL,
    full_name character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16446)
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4915 (class 0 OID 16488)
-- Dependencies: 222
-- Data for Name: contacts; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.contacts (id, address, created_at, email, first_name, is_favourite, last_name, phone, updated_at, user_id) FROM stdin;
36	Gulistan e johar Block-15	2026-07-27 03:20:51.233731	shahab@gmail.com	Shahab	f	Khan	03312166331	2026-07-27 03:20:51.233731	6
37	Liaquatabad no. 5	2026-07-27 03:20:51.258232	saleem@gmail.com	Saleem	t	Sheikh	03412044451	2026-07-27 03:21:50.806298	6
34	Shahrah e faisal Block-2A	2026-07-27 03:20:51.183758	fasih@gmail.com	Fasih	t		03332166754	2026-07-27 03:21:56.638023	6
39	karimabad sunehra Apartment	2026-07-27 03:22:36.192025	ahmali@gmail.com	Ahmed	f	Ali	03322177754	2026-07-27 03:22:36.192025	6
42	N-18 Block 12, Gulistan e johar, Karachi	2026-07-27 04:12:25.48436	noemahmedkhan8307@gmail.com	Noem	f	Khan	+923452971536	2026-07-27 04:12:25.48436	6
28	karimabad sunehra Apartment	2026-07-05 04:52:51.470737	ahmali@gmail.com	Ahmed	f	Ali	03322177754	2026-07-05 04:52:51.470737	4
29	Gulistan e johar Block-15	2026-07-05 04:52:51.493724	shahab@gmail.com	Shahab	f	Khan	03312166331	2026-07-05 04:52:51.494724	4
27	Shahrah e faisal Block-2A	2026-07-05 04:52:51.402777	fasih@gmail.com	Fasih	t		03332166754	2026-07-05 04:53:03.933821	4
30	Liaquatabad no. 5	2026-07-05 04:52:51.518712	saleem@gmail.com	Saleem	t	Sheikh	03412044451	2026-07-05 04:53:05.303887	4
31	F-51/8, F.C Area, Liaquatabad, Karachi	2026-07-05 04:54:01.45584	noemahmedkhan8307@gmail.com	Munaim	f	Khan	+923452971536	2026-07-05 04:54:01.45584	4
45	Block-5	2026-07-30 21:44:08.961792	ahmali@gmail.com	Ahmed	f	Ali	03322177754	2026-07-30 21:44:08.961792	7
33	F.C Area, Liaquatabad, Karachi	2026-07-27 03:18:30.295028	munaim@gmail.com	Munaim Ahmed	t	Khan	+923452971555	2026-07-27 03:20:09.598878	6
46	Block-12	2026-07-30 21:44:08.977782	shahab@gmail.com	Shahab	f	Khan	03312166331	2026-07-30 21:44:08.977782	7
43	Street 123	2026-07-30 21:43:54.0723	salman@gmail.com	Salman	t	Ahmed	03441008521	2026-07-30 21:44:20.489556	7
47	Block-15	2026-07-30 21:44:08.993373	saleem@gmail.com	Fawad	t		03412044451	2026-07-30 21:44:43.284077	7
\.


--
-- TOC entry 4913 (class 0 OID 16447)
-- Dependencies: 220
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, created_at, email, full_name, password, updated_at) FROM stdin;
1	2026-06-27 03:55:31.965523	aslam@gmail.com	Aslam	$2a$10$.YxUr2UZUi/8BocoiYUobOX1AqMJdNpvPdhSKNPXgeaaTLlOZFgSq	2026-06-27 03:55:31.965523
2	2026-06-27 04:15:59.44272	farooq@gmail.com	Farooq	$2a$10$L38.KjXo4WBIKRspXXkhee7kS9WDAmzqoCyJbhkOfb7mxLncv8Zq6	2026-06-27 04:15:59.44272
4	2026-06-30 01:44:32.935476	noemahmedkhan8307@gmail.com	Noem Ahmed	$2a$10$J8bgTIhubYbIPvct4.ZuwOlSnopBVHpuAmxnMzHIzIBwc4uoWP0uO	2026-07-03 03:49:18.674647
5	2026-07-24 03:35:34.937987	junaid@gmail.com	Junaid Khan	$2a$10$/TqW55LrBQ6txFaJz4h9IumWKZgYOQ7KVNRQsXMLKyamdMKTGuzPG	2026-07-24 03:35:34.937987
6	2026-07-27 03:12:40.292264	haroon1@gmail.com	Mr. Haroon Ahmed	$2a$10$jCHgt1V3WWC7agnB7VVpbuTE1arvLSlEoE8hJ4tFz4B/GRr5wiApW	2026-07-27 03:14:39.855896
7	2026-07-30 21:42:44.264644	ahmed@gmail.com	Ahmed	$2a$10$IimCJPrGSGB7XT0JsF1JoumfcfCquy1CmYi19YsbBfEDIO8Dx4ExW	2026-07-30 21:43:18.850172
\.


--
-- TOC entry 4922 (class 0 OID 0)
-- Dependencies: 221
-- Name: contacts_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.contacts_id_seq', 47, true);


--
-- TOC entry 4923 (class 0 OID 0)
-- Dependencies: 219
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 7, true);


--
-- TOC entry 4763 (class 2606 OID 16502)
-- Name: contacts contacts_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contacts
    ADD CONSTRAINT contacts_pkey PRIMARY KEY (id);


--
-- TOC entry 4761 (class 2606 OID 16459)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 4764 (class 2606 OID 16503)
-- Name: contacts fkna8bddygr3l3kq1imghgcskt8; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contacts
    ADD CONSTRAINT fkna8bddygr3l3kq1imghgcskt8 FOREIGN KEY (user_id) REFERENCES public.users(id);


-- Completed on 2026-07-30 23:10:49

--
-- PostgreSQL database dump complete
--

\unrestrict AY6Db4az4u9AhcN7pvMphBrH0iJ5dYK7GoguTT9l3JFyW6M1y3JxqsbREG6aZst

